// © 2026 Youssef Ismail. All rights reserved.
// LIMENX is proprietary software. Published for portfolio review only —
// not licensed for reuse, redistribution, or derivative works.
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metrics */
        get: operations["metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Version */
        get: operations["version_v1_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Info */
        get: operations["info_v1_info_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/predict": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Predict */
        post: operations["predict_v1_predict_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/predict/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Predict Batch */
        post: operations["predict_batch_v1_predict_batch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BatchPredictRequest
         * @example {
         *       "include_explanation": false,
         *       "urls": [
         *         "google.com",
         *         "paypa1-secure-login.tk/verify",
         *         "ftp://x.test/a"
         *       ]
         *     }
         */
        BatchPredictRequest: {
            /**
             * Urls
             * @description URLs to score (≤ configured max_batch).
             */
            urls: string[];
            /**
             * Include Explanation
             * @default false
             */
            include_explanation: boolean;
        };
        /** BatchResponse */
        BatchResponse: {
            /** Results */
            results: components["schemas"]["PredictResponse"][];
            summary: components["schemas"]["BatchSummary"];
        };
        /** BatchSummary */
        BatchSummary: {
            /** N */
            n: number;
            /** Scored */
            scored: number;
            /** Invalid */
            invalid: number;
            /** Error */
            error: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InfoResponse */
        InfoResponse: {
            /** Service */
            service: string;
            /** Status */
            status: string;
            /** Model */
            model: string;
        };
        /**
         * PredictRequest
         * @example {
         *       "include_explanation": true,
         *       "url": "paypa1-secure-login.tk/verify/account"
         *     }
         * @example {
         *       "include_explanation": false,
         *       "url": "https://www.wikipedia.org/wiki/Phishing"
         *     }
         */
        PredictRequest: {
            /**
             * Url
             * @description The URL to score (raw; scheme optional — a missing scheme is assumed https).
             */
            url: string;
            /**
             * Include Explanation
             * @description Attach risk/reasons/contributions (requires explain:full scope when auth is enabled).
             * @default false
             */
            include_explanation: boolean;
        };
        /**
         * PredictResponse
         * @description Typed mirror of ScoreResult.as_dict() (fail-closed statuses included).
         * @example {
         *       "decision": true,
         *       "explanation_status": "ok",
         *       "explanation_version": "v1.0",
         *       "latency_ms": 12.3,
         *       "member_contributions": [
         *         {
         *           "contribution": 0.2,
         *           "member": "cnn"
         *         }
         *       ],
         *       "member_scores": {
         *         "cb": 0.87,
         *         "cnn": 0.99,
         *         "rf": 0.98,
         *         "t": 0.95
         *       },
         *       "model_version": "v3.4",
         *       "operating_threshold": 0.4678,
         *       "probability": 0.9997,
         *       "reasons": [
         *         {
         *           "code": "feature:suspicious_tld",
         *           "direction": "toward_phishing",
         *           "faithfulness": "exact",
         *           "source": "feature",
         *           "title": "Suspicious top-level domain"
         *         }
         *       ],
         *       "scheme_assumed": true,
         *       "scheme_resolution": "assumed_https",
         *       "status": "scored",
         *       "threat_level": "critical",
         *       "url_input": "paypa1-secure-login.tk/verify",
         *       "url_normalized": "https://paypa1-secure-login.tk/verify"
         *     }
         */
        PredictResponse: {
            /** Status */
            status: string;
            /** Url Input */
            url_input?: string | null;
            /** Url Normalized */
            url_normalized: string;
            /** Model Version */
            model_version: string;
            /** Probability */
            probability?: number | null;
            /** Decision */
            decision?: boolean | null;
            /** Operating Threshold */
            operating_threshold?: number | null;
            /** Member Scores */
            member_scores?: {
                [key: string]: number;
            } | null;
            /** Scheme Assumed */
            scheme_assumed?: boolean | null;
            /** Scheme Resolution */
            scheme_resolution?: string | null;
            /** Reasons */
            reasons?: {
                [key: string]: unknown;
            }[] | null;
            /** Threat Level */
            threat_level?: string | null;
            /** Member Contributions */
            member_contributions?: {
                [key: string]: unknown;
            }[] | null;
            /** Explanation Status */
            explanation_status?: string | null;
            /** Explanation Version */
            explanation_version?: string | null;
            /** Detail */
            detail?: string | null;
            /** Latency Ms */
            latency_ms?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VersionResponse */
        VersionResponse: {
            /** Api Version */
            api_version: string;
            /** Model Version */
            model_version: string;
            /** Explanation Version */
            explanation_version: string;
            /** Available Model Versions */
            available_model_versions?: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    metrics_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    version_v1_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionResponse"];
                };
            };
        };
    };
    info_v1_info_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InfoResponse"];
                };
            };
        };
    };
    predict_v1_predict_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PredictRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    predict_batch_v1_predict_batch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchPredictRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
